#+title: 如何做笔记
* 我们做笔记的目的是什么

* 简述
选择印象笔记的原因有很多,正当我想使用 org-mode 去完成笔记管理的时候,选择印象笔记还是选择 org-mode 笔记的问题就浮现出来,就目前而言,我使用印象笔记仅仅用到了简单的几项功能
- 快速记录笔记
- 多平台同步
- 快速查找笔记
- 
- 
在这几项功能中,我最频繁使用的就是 快速记录笔记/快速查找笔记/多平台同步 这几项功能,
因为我希望我能够在我触手可及的地方随时记录我想记录的东西.
此外,对这些东西我也想要随时能够查到.不过这仅仅是简单而零碎的信息缓存而已.
要想让这些信息产生更大的价值还远不够,但是更多的信息我就不知道该怎么处理了

** 以写论文为例

前期我需要整理素材,了解最近几年的研究进展,并且从中发现别人做的少或者没有做过的东西
然后我又要对这些内容进行加工内化成为我对某个方面的认知,并且从中发现一些我还没有认知的东西
接着我就能开始着实做一些事情去验证我的没认知的东西
将这个结果写成论文并交给别人来审阅
事后我对这些素材及论文进行整理归档
这就是整个撰写论文的流程了

抛开写论文做项目这些东西而言
我加工某些信息的目的是什么呢
是对我自己将面对的未知事物进行决策
比如我不知道某样东西是好的还是不好的
我就需要从其他地方去获取信息,别人对这个东西是怎么评价的
他们为什么这么评价,我觉得他们评价的对吗,我为什么这么觉得呢?

** 所以这么一看,信息反而不是很重要,重要的是对信息的加工,是知识
但是知识并不是一层不变的,它是从信息中一步步加工过来的,那如果信息有变化,知识也会出现相应的变化

虽然我不知道我写了什么,但是我觉得一旦想明白了这里面的一些问题,那么是选择印象笔记还是选择 org-mode
对我来讲影响都不大的,因为我能够利用好这两个工具,而不是成为工具的奴隶

那么在记笔记这件事情上,到底什么是最重要的事情?
** 记笔记这件事情上,什么是最重要的事情?
* 关于笔记工具,我们需要的是什么
** 快速查找
   - web端
   - linux 端
   - 手机端
   - windows端
   其实最快的查找方法是文件内容查找工具,可以是spacemacs,也可以是命令行
   一般通过grep就能够查找到所有的文字,定位非常快捷.
   手机端/web端/windows端的话需要特殊软件支持

   结论:手机不适合记录笔记和日程管理
